/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <jni.h>
/* Header for class com_android_rtmpvideo_YuvOperateJni */

#ifndef _Included_YuvOperateJni
#define _Included_YuvOperateJni
#ifdef __cplusplus
extern "C" {
#endif

#include "yuvengine/yuvengine.h"
/*
 * Class:     com_han_rtmpandroid_utils_YuvConvertor
 * Method:    Yv12ToI420
 * Signature: (J[B[BII)V
 */
JNIEXPORT void JNICALL Java_com_han_rtmpandroid_utils_YuvConvertor_Yv12ToI420
  (JNIEnv *, jobject , jbyteArray, jbyteArray, jint, jint);

/*
 * Class:     com_han_rtmpandroid_utils_YuvConvertor
 * Method:    I420ToYv12
 * Signature: (J[B[BII)V
 */
JNIEXPORT void JNICALL Java_com_han_rtmpandroid_utils_YuvConvertor_I420ToYv12
  (JNIEnv *, jobject,  jbyteArray, jbyteArray, jint, jint);

/*
 * Class:     com_han_rtmpandroid_utils_YuvConvertor
 * Method:    Nv21ToI420
 * Signature: (J[B[BII)V
 */
JNIEXPORT void JNICALL Java_com_han_rtmpandroid_utils_YuvConvertor_Nv21ToI420
  (JNIEnv *, jobject,  jbyteArray, jbyteArray, jint, jint);

/*
 * Class:     com_han_rtmpandroid_utils_YuvConvertor
 * Method:    I420ToNv21
 * Signature: (J[B[BII)V
 */
JNIEXPORT void JNICALL Java_com_han_rtmpandroid_utils_YuvConvertor_I420ToNv21
  (JNIEnv *, jobject,  jbyteArray, jbyteArray, jint, jint);

/*
 * Class:     com_han_rtmpandroid_utils_YuvConvertor
 * Method:    Nv21ToYv12
 * Signature: (J[B[BII)V
 */
JNIEXPORT void JNICALL Java_com_han_rtmpandroid_utils_YuvConvertor_Nv21ToYv12
  (JNIEnv *, jobject,  jbyteArray, jbyteArray, jint, jint);

/*
 * Class:     com_han_rtmpandroid_utils_YuvConvertor
 * Method:    YV12ToNv21
 * Signature: (J[B[BII)V
 */
JNIEXPORT void JNICALL Java_com_han_rtmpandroid_utils_YuvConvertor_YV12ToNv21
  (JNIEnv *, jobject,  jbyteArray, jbyteArray, jint, jint);

/*
 * Class:     com_han_rtmpandroid_utils_YuvConvertor
 * Method:    Nv21ToNv12
 * Signature: (J[B[BII)V
 */
JNIEXPORT void JNICALL Java_com_han_rtmpandroid_utils_YuvConvertor_Nv21ToNv12
  (JNIEnv *, jobject,  jbyteArray, jbyteArray, jint, jint);

/*
 * Class:     com_han_rtmpandroid_utils_YuvConvertor
 * Method:    Nv12ToNv21
 * Signature: (J[B[BII)V
 */
JNIEXPORT void JNICALL Java_com_han_rtmpandroid_utils_YuvConvertor_Nv12ToNv21
  (JNIEnv *, jobject,  jbyteArray, jbyteArray, jint, jint);

/*
 * Class:     com_han_rtmpandroid_utils_YuvConvertor
 * Method:    CutCommonYuv
 * Signature: (JIII[BII[BII)V
 */
JNIEXPORT void JNICALL Java_com_han_rtmpandroid_utils_YuvConvertor_CutCommonYuv
  (JNIEnv *, jobject,  jint, jint, jint, jbyteArray, jint, jint, jbyteArray, jint, jint);

/*
 * Class:     com_han_rtmpandroid_utils_YuvConvertor
 * Method:    GetSpecYuvBuffer
 * Signature: (JI[B[BIIII)V
 */
JNIEXPORT void JNICALL Java_com_han_rtmpandroid_utils_YuvConvertor_GetSpecYuvBuffer
  (JNIEnv *, jobject,  jint, jbyteArray, jbyteArray, jint, jint, jint, jint);

/*
 * Class:     com_han_rtmpandroid_utils_YuvConvertor
 * Method:    YuvAddWaterMark
 * Signature: (JIII[BII[BII)V
 */
JNIEXPORT void JNICALL Java_com_han_rtmpandroid_utils_YuvConvertor_YuvAddWaterMark
  (JNIEnv *, jobject,  jint, jint, jint, jbyteArray, jint, jint, jbyteArray, jint, jint);

/*
 * Class:     com_han_rtmpandroid_utils_YuvConvertor
 * Method:    Nv21ClockWiseRotate90
 * Signature: (J[BII[B[I[I)V
 */
JNIEXPORT void JNICALL Java_com_han_rtmpandroid_utils_YuvConvertor_Nv21ClockWiseRotate90
  (JNIEnv *, jobject,  jbyteArray, jint, jint, jbyteArray, jintArray, jintArray);

/*
 * Class:     com_han_rtmpandroid_utils_YuvConvertor
 * Method:    Nv12ClockWiseRotate90
 * Signature: (J[BII[B[I[I)V
 */
JNIEXPORT void JNICALL Java_com_han_rtmpandroid_utils_YuvConvertor_Nv12ClockWiseRotate90
  (JNIEnv *, jobject,  jbyteArray, jint, jint, jbyteArray, jintArray, jintArray);

/*
 * Class:     com_han_rtmpandroid_utils_YuvConvertor
 * Method:    Nv21ClockWiseRotate180
 * Signature: (J[BII[B[I[I)V
 */
JNIEXPORT void JNICALL Java_com_han_rtmpandroid_utils_YuvConvertor_Nv21ClockWiseRotate180
  (JNIEnv *, jobject,  jbyteArray, jint, jint, jbyteArray, jintArray, jintArray);

/*
 * Class:     com_han_rtmpandroid_utils_YuvConvertor
 * Method:    Nv21ClockWiseRotate270
 * Signature: (J[BII[B[I[I)V
 */
JNIEXPORT void JNICALL Java_com_han_rtmpandroid_utils_YuvConvertor_Nv21ClockWiseRotate270
  (JNIEnv *, jobject,  jbyteArray, jint, jint, jbyteArray, jintArray, jintArray);

/*
 * Class:     com_han_rtmpandroid_utils_YuvConvertor
 * Method:    I420ClockWiseRotate90
 * Signature: (J[BII[B[I[I)V
 */
JNIEXPORT void JNICALL Java_com_han_rtmpandroid_utils_YuvConvertor_I420ClockWiseRotate90
  (JNIEnv *, jobject,  jbyteArray, jint, jint, jbyteArray, jintArray, jintArray);

/*
 * Class:     com_han_rtmpandroid_utils_YuvConvertor
 * Method:    Yv12ClockWiseRotate90
 * Signature: (J[BII[B[I[I)V
 */
JNIEXPORT void JNICALL Java_com_han_rtmpandroid_utils_YuvConvertor_Yv12ClockWiseRotate90
  (JNIEnv *, jobject,  jbyteArray, jint, jint, jbyteArray, jintArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
